# Generated by Django 5.2 on 2025-05-08 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0003_resitexamcontent_resitexamschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resitexamschedule',
            name='time',
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resitexamschedule',
            name='date',
            field=models.DateField(),
        ),
    ]
